version: '3'

services:
    grafana:
        image: grafana/grafana:latest
        user: '104'
        ports:
            - '3000:3000'
        volumes:
            - ./gfdata:/var/lib/grafana
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db-init-scripts:/docker-entrypoint-initdb.d

    strava-data-provider:
        build: .
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
            STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - '5050:80'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres

volumes:
    postgres_data:
    pgadmin-data:
