{
 "title": "Performances Challenge",
 "time": { "from": "2023-05-06T22:00:00.000Z", "to": "2023-08-31T21:59:59.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(ath.first_name, ' ', ath.last_name) AS \"Nom Athlète\", MAX(a.distance_run::numeric) AS \"Plus longue distance\",  MAX(a.time_run::numeric) AS \"Temps couru le plus long\"\nFROM activities a\nJOIN athletes ath ON ath.id = a.athlete_id\nGROUP BY ath.id, ath.first_name, ath.last_name\nORDER BY \"Plus longue distance\" DESC;"
    }
   ]
  },
  {
   "title": "Dernière Courses",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT r.date AS \"Heure de la course\", r.distance_run AS \"Distance (km)\",r.time_run AS \"Temps (min)\",r.speed_run AS \"Vitesse\", CONCAT(a.first_name, ' ', a.last_name) AS \"Nom Athlète\"\nFROM activities r\nJOIN athletes a ON r.athlete_id = a.id\nORDER BY r.date DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Kilomètres totaux",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(distance_run AS numeric)) AS total_distance\nFROM activities;"
    }
   ]
  },
  {
   "title": "Athlètes",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Id Strava\", first_name AS \"Prénom\", last_name AS \"Nom\" FROM athletes LIMIT 50 "
    }
   ]
  },
  {
   "title": "Distance Cumulative par athlète",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT a.first_name, a.last_name, date,\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Nicolas B.') OVER (ORDER BY date) AS \"Nicolas\",\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Kévin L.') OVER (ORDER BY date) AS \"Kévin\",\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Theo L.') OVER (ORDER BY date) AS \"Théo\"\nFROM athletes a\nJOIN activities ac ON a.id = ac.athlete_id\nORDER BY date;"
    }
   ]
  }
 ]
}