apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    orgId: 1
    url: ${POSTGRES_HOST}:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      # sslmode: "disable"
      sslmode: "require"
      database: ${POSTGRES_DB}