{
 "title": "Bike Challenge",
 "description": "Challenge Strava",
 "time": { "from": "2025-04-30T22:00:00.000Z", "to": "2025-08-31T21:59:59.000Z" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(ath.first_name, ' ', ath.last_name) AS \"Nom Athlète\", MAX(a.distance::numeric) AS \"Distance Max\", MAX(a.time::numeric) AS \"Temps Max\", MAX(a.elevation_gain::numeric) AS \"D+ max\", AVG(a.speed::numeric) AS \"Vitesse Moyenne\"\nFROM \"bikeActivities\" a\nJOIN athletes ath ON ath.id = a.athlete_id\nGROUP BY ath.id, ath.first_name, ath.last_name\nORDER BY \"Distance Max\" DESC;"
    }
   ]
  },
  {
   "title": "Dernière Courses",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT r.date AS \"Heure de la course\", CONCAT(a.first_name, ' ', a.last_name) AS \"Nom Athlète\", r.distance AS \"Distance\",r.time AS \"Temps\",r.speed AS \"Vitesse\",r.elevation_gain AS \"Dénivelé positif\" FROM \"bikeActivities\" r JOIN athletes a ON r.athlete_id = a.id ORDER BY r.date DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Kilomètres totaux",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(time) AS total_distance FROM \"bikeActivities\";"
    }
   ]
  },
  {
   "title": "Temps total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(time) AS total_distance FROM \"bikeActivities\";"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(a.first_name, ' ', a.last_name) AS \"Nom\", COUNT(*) AS \"Nbre courses\", AVG(act.elevation_gain) AS \"Déniv Moyen\", AVG(act.time) AS \"Temps Moyen\", AVG(act.distance) AS \"Distance moyenne\"\nFROM athletes a\nJOIN \"bikeActivities\" act ON act.athlete_id = a.id\nGROUP BY a.id, \"Nom\"\nORDER BY \"Nbre courses\" DESC;"
    }
   ]
  },
  {
   "title": "Vitesse moyenne",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(speed) AS avg_vitesse FROM \"bikeActivities\";"
    }
   ]
  },
  {
   "title": "Distance Cumulative par athlète",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH cumulative_data AS (\n    SELECT\n        date,\n        a.id,\n        CONCAT(a.first_name, ' ', a.last_name) AS athlete_name,\n        SUM(CAST(distance AS numeric)) OVER (PARTITION BY a.id ORDER BY date) AS cumulative_distance\n    FROM athletes a\n    JOIN \"bikeActivities\" ac ON a.id = ac.athlete_id\n)\nSELECT\n    date,\n    jsonb_object_agg(athlete_name, cumulative_distance) AS athletes_data\nFROM cumulative_data\nGROUP BY date\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Dénivelé Positif Cumulatif par athlète",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH cumulative_data AS (\n    SELECT\n        date,\n        a.id,\n        CONCAT(a.first_name, ' ', a.last_name) AS athlete_name,\n        SUM(CAST(elevation_gain AS numeric)) OVER (PARTITION BY a.id ORDER BY date) AS cumulative_elevation\n    FROM athletes a\n    JOIN \"bikeActivities\" ac ON a.id = ac.athlete_id\n)\nSELECT\n    date,\n    jsonb_object_agg(athlete_name, cumulative_elevation) AS athletes_data\nFROM cumulative_data\nGROUP BY date\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Athlètes",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Id Strava\", first_name AS \"Prénom\", last_name AS \"Nom\" FROM athletes LIMIT 50"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(a.first_name, ' ', a.last_name) AS \"Nom Athlète\", \n       SUM(CAST(act.distance AS DECIMAL)) AS \"Distance Totale\", \n       SUM(CAST(act.elevation_gain AS DECIMAL)) AS \"D+ Total\",\n       SUM(CAST(act.time AS DECIMAL)) AS \"Temps Total\"\nFROM athletes a\nJOIN \"bikeActivities\" act ON act.athlete_id = a.id\nGROUP BY a.id, \"Nom Athlète\"\nORDER BY \"Distance Totale\" DESC;"
    }
   ]
  }
 ]
}