{
 "title": "Performances Challenge",
 "time": { "from": "2023-05-08 23:59:59", "to": "2023-08-31 23:59:59" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(ath.first_name, ' ', ath.last_name) AS \"Nom Athlète\", MAX(a.distance_run::numeric) AS \"Distance Max\",  MAX(a.time_run::numeric) AS \"Temps Max\", AVG(a.speed_run::numeric) AS \"Vitesse Moyenne\"\nFROM activities a\nJOIN athletes ath ON ath.id = a.athlete_id\nGROUP BY ath.id, ath.first_name, ath.last_name\nORDER BY \"Distance Max\" DESC;"
    }
   ]
  },
  {
   "title": "Dernière Courses",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT r.date AS \"Heure de la course\", r.distance_run AS \"Distance\",r.time_run AS \"Temps\",r.speed_run AS \"Vitesse\", CONCAT(a.first_name, ' ', a.last_name) AS \"Nom Athlète\"\nFROM activities r\nJOIN athletes a ON r.athlete_id = a.id\nORDER BY r.date DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Kilomètres totaux",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(distance_run AS numeric)) AS total_distance\nFROM activities;"
    }
   ]
  },
  {
   "title": "Temps totaux",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(time_run) AS total_distance\nFROM activities;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(a.first_name, ' ', a.last_name) AS \"Nom\", COUNT(*) AS \"Nombre de courses\",  AVG(act.time_run) AS \"Temps Moyen\", AVG(act.distance_run)  AS \"Distance moyenne\"\nFROM athletes a\nJOIN activities act ON act.athlete_id = a.id\nGROUP BY a.id, \"Nom\"\nORDER BY \"Nombre de courses\" DESC;"
    }
   ]
  },
  {
   "title": "Vitesse moyenne",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(speed_run) AS avg_vitesse\nFROM activities;"
    }
   ]
  },
  {
   "title": "Distance Cumulative par athlète",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT a.first_name, a.last_name, date,\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Nicolas B.') OVER (ORDER BY date) AS \"Nicolas\",\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Kévin L.') OVER (ORDER BY date) AS \"Kévin\",\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Theo L.') OVER (ORDER BY date) AS \"Théo\",\n       SUM(CAST(distance_run AS numeric)) FILTER (WHERE a.id = 'Nathanael D.') OVER (ORDER BY date) AS \"Nathanaël\"\nFROM athletes a\nJOIN activities ac ON a.id = ac.athlete_id\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Athlètes",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Id Strava\", first_name AS \"Prénom\", last_name AS \"Nom\" FROM athletes LIMIT 50 "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(a.first_name, ' ', a.last_name) AS \"Nom Athlète\", SUM(CAST(act.distance_run AS DECIMAL)) AS \"Distance Totale\",SUM(CAST(act.time_run AS DECIMAL)) AS \"Temps Total\"\nFROM athletes a\nJOIN activities act ON act.athlete_id = a.id\nGROUP BY a.id, \"Nom Athlète\"\nORDER BY \"Distance Totale\" DESC;"
    }
   ]
  }
 ]
}